### ISSUE TITLE
missing Color  widget?

### ISSUE THREAD

**Issue by cekees** [jdfreder/ipython-papershape#2]
I'm trying to run this with IPython 3.1.0, but it looks like I'm missing widgets.Color. If I comment that out, things look like they're working, but the line segments don't show up.

**Comment by jdfreder** [comment]
Hey Chris, that's a relatively new traitlet type @sylvaincorlay added.  Sorry, I must be running a slightly different version of the notebook than you.  While developing this, I was running the latest 3.x.  Color is just a strict unicode type which validates that the string is indeed a color.

**Comment by SylvainCorlay** [comment]
@cekees in IPython 3.1.0, widgets are still parts of IPython core.
~~This repository is the result of a repository split that happened in IPython to separate projects scope and concerns. You should probably not install this repository with IPython 3.1.0.~~

**Comment by jdfreder** [comment]
No it's okay, I just removed the Color reference.  It should work fine with his version of IPython now.  I'm just running a slightly new version - 3.2 dev instead of 3.0 or 3.1.

**Comment by SylvainCorlay** [comment]
@jdfreder I backported the color trait to 3.2. 
sorry, thought this was a bug in ipython/ipywidgets.

**Comment by cekees** [comment]
Thanks for looking at it.  I figured the Color widget was just  a bit  on top of Unicode, but I couldn't get it right when I tried switching the trait to Unicode.
