### ISSUE TITLE
segment splitter box not active for me on linux

### ISSUE THREAD

**Issue by cekees** [jdfreder/ipython-papershape#3]
One other  thing I noticed is that  I can't seem to split segments as in your demo. It may just be related to #2

**Comment by jdfreder** [comment]
Can you see if #4 fixes this?

To split a line, hover over the dotted green box and left click.  Left clicking once creates the blue box that you can drag around.  Note that this is two step, left click and then drag, not left click drag.

**Comment by cekees** [comment]
That  fixes the line segment colors, but I still can't split segments. When I hover over the dotted  green box and left  click I don't get the blue box.

**Comment by jdfreder** [comment]
What browser and browser version are you using?

**Comment by cekees** [comment]
I tried with Firefox 37.0.2, Chrome 42.0.2311.152,  and Chromium  41.0.2272.76
Ubuntu 14.04 (64-bit)

**Comment by jdfreder** [comment]
Also thinking this could be installation related.  The default behavior for the installer is to copy the JS over.  When using pip, the -e flag tells it to symlink the Javascript.  WRT to you, since `pip install -e .` wasn't working, you probably installed using `python setup.py install`, right?  If so you need to reinstall to see the changes to the Javascript.  - Just run `python setup.py install` again, it should copy the new JS over the old one.

**Comment by cekees** [comment]
Still not getting the points adding behavior after re-installing. There are no errors  in the javascript  console. Makes   me think  it's a mouse click  binding issue that is somehow different on linux and mac.

**Comment by jdfreder** [comment]
Hmm could be, I just tried on Windows 7 with FF 37 and Chrome 42 and didn't have trouble.  I'll try another mouse event binding method, even though I'm using JQuery's .click now, which is supposed to take care of all the cross platform issues.

**Comment by cekees** [comment]
Now I'm thinking that the right click is being captured by the browser or  OS window manager for the application context menu. I should probably look at JQuery's mouse/keyboard capture stuff  and your js for attaching it to the paper api, so maybe I should experiment with some different bindings.

**Comment by jdfreder** [comment]
#8 should close this : )
